#pragma once
/* Generated by client_generic/WinBuild/build.py — do not edit by hand. */

#define EDREAM_BUILD_VERSION_SEMVER "0.1.0"
#define EDREAM_BUILD_GIT_REVISION "6fe1bb11"
#define EDREAM_BUILD_DATE_UTC "Mon May 11 08:09:06 UTC 2026"
