#pragma once
/* Generated by client_generic/WinBuild/build.py — do not edit by hand. */

#define EDREAM_BUILD_VERSION_SEMVER "0.14.11"
#define EDREAM_BUILD_GIT_REVISION "c28dcbc6"
#define EDREAM_BUILD_DATE_UTC "Sun Apr 26 13:33:21 UTC 2026"
