#pragma once
/* Generated by client_generic/WinBuild/build.py — do not edit by hand. */

#define EDREAM_BUILD_VERSION_SEMVER "0.14.10"
#define EDREAM_BUILD_GIT_REVISION "52c5e7f6"
#define EDREAM_BUILD_DATE_UTC "Mon Apr 20 21:42:03 UTC 2026"
