/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "n6.1.1-93-g9593b727e2-20240420"
#endif /* AVUTIL_FFVERSION_H */
